### ISSUE TITLE
build.py `--revision` flag from microbit-v2-samples

### ISSUE THREAD

**Issue by carlosperate** [lancaster-university/codal#49]
Just noticed the micro:bit version of build.py has an extra flag: https://github.com/lancaster-university/microbit-v2-samples/commit/9da3427ce4805cc99e98d117e6b0bad14f14cd72

We might want to add it to this repo as well, specially if micro:bit adopts the bootstrap.

**Comment by carlosperate** [comment]
There is also this commit that should be applied here as well:
- https://github.com/lancaster-university/microbit-v2-samples/commit/49f6dddad79b924092fea6b89fdd67da0ee218bd

**Comment by microbit-carlos** [comment]
https://github.com/lancaster-university/microbit-v2-samples/commit/49f6dddad79b924092fea6b89fdd67da0ee218bd has been implemented here already, and https://github.com/lancaster-university/microbit-v2-samples/commit/9da3427ce4805cc99e98d117e6b0bad14f14cd72 has been added to this list:
- https://github.com/lancaster-university/codal/issues/54 

So we can close this one 👍
